"""Every coordination wait in tests/ that does not yet use `waiting`, and the product-deadline
values that look like one.

Built for the test reliability sprint (docs/sprints/2026-09-22-test-reliability/). Each entry is
(file, function, source line, status, reason). A `pending-02` or `pending-03` entry is a
coordination wait that chunk 02 or 03 converts to `waiting` and then removes from this list; a
file that chunk 02 does not name belongs to chunk 03. A `product-deadline` entry stays, with its
reason. `test_wait_inventory` checks this list against the source.
"""
DATA = 'product data: a deadline or expiry value passed to the code under test, not a wait'

ENTRIES = [
    ('test_bridge_startup.py', 'BridgeStartupTests.test_serve_cli_refuses_live_endpoint_without_creating_database',
     'stdout, stderr = await asyncio.wait_for(process.communicate(), 5)',
     'pending-02', ''),
    ('test_bridge_startup.py', 'BridgeStartupTests.test_unsafe_state_root_cli_is_structured',
     'stdout, stderr = await asyncio.wait_for(process.communicate(), 5)',
     'pending-02', ''),
    ('test_bridge_startup.py', 'BridgeStartupTests.test_invalid_filesystem_paths_are_structured_cli_refusals',
     'stdout, stderr = await asyncio.wait_for(process.communicate(), 5)',
     'pending-02', ''),
    ('test_bridge_startup.py', 'BridgeStartupTests.test_reservation_survives_database_close_and_normal_start_serves',
     'async with asyncio.timeout(3):',
     'pending-02', ''),
    ('test_component_install.py', 'ComponentInstallTests.test_fresh_explicit_repository_thread_selects_both_components',
     'result = subprocess.run(command, env=self.env, capture_output=True, text=True, timeout=20)',
     'pending-03', ''),
    ('test_component_install.py', 'ComponentInstallTests.test_existing_guidance_install_does_not_silently_add_memory',
     'first = subprocess.run(base, env=self.env, capture_output=True, text=True, timeout=20)',
     'pending-03', ''),
    ('test_component_install.py', 'ComponentInstallTests.test_interrupted_fresh_install_retains_component_intent_on_retry',
     'resumed = subprocess.run([sys.executable, *command], capture_output=True, text=True, timeout=20)',
     'pending-03', ''),
    ('test_database_worker.py', 'reached',
     'async with asyncio.timeout(3):',
     'pending-02', ''),
    ('test_database_worker.py', 'WorkerTests.asyncSetUp.Owned.write',
     'if not test.release.wait(5):',
     'pending-02', ''),
    ('test_delivery_ledger.py', 'LedgerTests.test_outgoing_and_incoming_capacity_are_independent',
     "self.store.outgoing('uds:/tmp/target.sock', 'body', 'next', 'id', time.time()+60)",
     'product-deadline', DATA),
    ('test_delivery_ledger.py', 'LedgerTests.test_outgoing_and_incoming_capacity_are_independent',
     "self.store.outgoing('uds:/tmp/target.sock', 'body', 'next', 'other', time.time()+60)",
     'product-deadline', DATA),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_fetch_evidence_timeout_never_appends_a_second_reply.blocked',
     'release.wait(2)',
     'product-deadline', "holds the synthetic peer past the product's control deadline"),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_fetch_evidence_timeout_never_appends_a_second_reply',
     "self.assertEqual(await asyncio.wait_for(reader.read(), 1), b'')",
     'pending-02', ''),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_definite_connect_failure_is_durable_without_replay',
     'deadline = time.time()+60',
     'product-deadline', DATA),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_cancelled_native_send_is_never_replayed',
     'deadline = time.time() + 60',
     'product-deadline', DATA),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_cancelled_native_send_is_never_replayed',
     'await asyncio.wait_for(reached.wait(), 1)',
     'pending-02', ''),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_control_timeout_preserves_unknown_and_late_send_reservation.blocked',
     'release.wait(2)',
     'product-deadline', "holds the synthetic peer past the product's control deadline"),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_control_timeout_preserves_unknown_and_late_send_reservation',
     'deadline = time.time() + 60',
     'product-deadline', DATA),
    ('test_inbox_schema.py', 'SchemaPublicTests.test_startup_incompatible_and_corrupt_store_are_classified',
     'stdout, stderr = await asyncio.wait_for(process.communicate(), 5)',
     'pending-02', ''),
    ('test_inbox_schema.py', 'SchemaPublicTests.test_factory_programming_error_is_software_failure',
     'stdout, stderr = await asyncio.wait_for(process.communicate(), 5)',
     'pending-02', ''),
    ('test_memory.py', 'Base.note',
     "kw['deadline'] = time.time() + 600",
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_an_empty_snapshot_and_a_keyed_write_are_both_charged',
     "self.s.note('writer', 'finding', 'keyed', key='k1', deadline=time.time()+600)",
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_an_in_window_idempotency_key_is_never_evicted_to_make_room',
     'deadline = time.time() + 600',
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_the_retry_deadline_is_echoed_and_the_horizon_reported',
     'deadline = time.time() + 600',
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_deduplication_state_is_retained_only_to_its_deadline',
     "self.note('kept', key='fresh', deadline=time.time()+600)",
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_an_idempotent_write_requires_a_deadline_fixed_before_the_first_send',
     'deadline=time.time()+memory.IDEM_TTL+60)',
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_a_retry_after_its_deadline_is_refused_rather_than_appended',
     'deadline = time.time() + 0.3',
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_a_duplicate_carrying_a_changed_deadline_is_refused',
     'deadline = time.time() + 600',
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_the_reported_author_is_part_of_the_content_fingerprint',
     'deadline = time.time() + 600',
     'product-deadline', DATA),
    ('test_memory.py', 'LifecycleTests.kill_all',
     'p.wait(timeout=10)',
     'pending-03', ''),
    ('test_memory.py', 'LifecycleTests.wait_for_socket',
     'deadline = time.monotonic()+timeout',
     'pending-03', ''),
    ('test_memory.py', 'LifecycleTests.test_recovery_is_reachable_from_the_command_line',
     'stdout, stderr = client.communicate(timeout=20)',
     'pending-03', ''),
    ('test_memory.py', 'LifecycleTests.test_concurrent_first_start_elects_one_service',
     'deadline = time.monotonic()+30',
     'pending-03', ''),
    ('test_memory.py', 'LifecycleTests.test_an_unclean_exit_is_recovered_only_after_death_is_proved',
     'first.wait(timeout=10)',
     'pending-03', ''),
    ('test_memory.py', 'LifecycleTests.test_a_crash_between_commit_and_response_is_survived_and_recovered',
     'deadline = time.time() + 600',
     'product-deadline', DATA),
    ('test_memory.py', 'LifecycleTests.test_a_crash_between_commit_and_response_is_survived_and_recovered',
     'crasher.wait(timeout=10)',
     'pending-03', ''),
    ('test_memory.py', 'LifecycleTests.test_cli_records_scope_provenance_and_expiry',
     "'--expires',str(time.time()+3600)],capture_output=True,text=True)",
     'product-deadline', DATA),
    ('test_memory.py', 'LifecycleTests.test_stop_waits_for_the_service_to_exit_before_reporting',
     'service.wait(timeout=10)',
     'pending-03', ''),
    ('test_memory.py', 'LifecycleTests.test_a_request_in_flight_is_drained_before_the_store_closes',
     'service.wait(timeout=10)',
     'pending-03', ''),
    ('test_memory.py', 'LifecycleTests.test_guarded_stop_uses_the_captured_generation_and_reaps_the_child',
     'service.wait(timeout=10)',
     'pending-03', ''),
    ('test_memory.py', 'LifecycleTests.test_the_cli_can_continue_recall_and_status_pages',
     'deadline = str(time.time()+600)',
     'product-deadline', DATA),
    ('test_memory_bindings.py', 'IdentityMigrationTests.test_memory_migration_process_death_rolls_back_identity_and_version',
     "child = subprocess.run([sys.executable, '-c', source, str(path)], timeout=10)",
     'pending-02', ''),
    ('test_memory_bindings.py', 'IdentityMigrationTests.test_inbox_migration_process_death_rolls_back_columns_and_version',
     "child = subprocess.run([sys.executable, '-c', source, str(self.root)], timeout=10)",
     'pending-02', ''),
    ('test_memory_bindings.py', 'BindingPublicTests.asyncSetUp',
     'async with asyncio.timeout(3):',
     'pending-02', ''),
    ('test_memory_bindings.py', 'BindingPublicTests.asyncTearDown',
     'await asyncio.wait_for(asyncio.gather(*self.running), 4)',
     'pending-02', ''),
    ('test_memory_bindings.py', 'BindingPublicTests.legacy_length_boundary_service_case',
     'await asyncio.wait_for(running, 4)',
     'pending-02', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.cleanup_processes',
     'process.communicate(timeout=45)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.cleanup_processes',
     'process.communicate(timeout=5)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.wait_for',
     'deadline = time.monotonic() + timeout',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_real_child_readiness_stop_and_store_preservation',
     "stopped = subprocess.run(self.command('stop'), capture_output=True, text=True, timeout=50)",
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_real_child_readiness_stop_and_store_preservation',
     'process.communicate(timeout=10)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_external_memory_is_refused_without_stopping_or_adopting_it',
     'out, err = runner.communicate(timeout=25)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_external_memory_is_refused_without_stopping_or_adopting_it',
     'external.communicate(timeout=10)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_second_supervisor_refuses_while_first_keeps_its_child',
     'out, err = second.communicate(timeout=15)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_permanent_refusal_survives_restart_until_explicit_retry',
     'out, err = first.communicate(timeout=25)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_permanent_refusal_survives_restart_until_explicit_retry',
     'out, err = second.communicate(timeout=15)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_permanent_refusal_survives_restart_until_explicit_retry',
     "result = subprocess.run(self.command('ensure', '--retry'), capture_output=True, text=True, timeout=15)",
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_launchd_boundary_maps_permanent_failure_but_status_retains_it',
     'out, err = runner.communicate(timeout=25)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_launchd_boundary_maps_permanent_failure_but_status_retains_it',
     "status = subprocess.run(self.command('status'), capture_output=True, text=True, timeout=15)",
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_unwritable_refusal_still_maps_launchd_failure_to_clean_exit',
     'out, err = runner.communicate(timeout=25)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_unwritable_refusal_still_maps_launchd_failure_to_clean_exit',
     "status = subprocess.run(self.command('status'), capture_output=True, text=True, timeout=15)",
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_unwritable_refusal_still_maps_launchd_failure_to_clean_exit',
     'out, err = second.communicate(timeout=15)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_stop_during_backoff_prevents_another_child_start',
     "result = subprocess.run(self.command('stop'), capture_output=True, text=True, timeout=25)",
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_stop_during_backoff_prevents_another_child_start',
     'runner.communicate(timeout=10)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_stale_stop_request_does_not_stop_replacement_supervisor',
     "result = subprocess.run(self.command('stop'), capture_output=True, text=True, timeout=25)",
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_stale_stop_request_does_not_stop_replacement_supervisor',
     'first.communicate(timeout=10)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_zero_exit_without_child_readiness_is_not_adopted',
     'out, err = runner.communicate(timeout=25)',
     'pending-03', ''),
    ('test_memory_service.py', 'MemorySupervisorTests.test_ensure_is_read_only_and_never_reports_unstarted_service_running',
     "result = subprocess.run(self.command('ensure'), capture_output=True, text=True, timeout=15)",
     'pending-03', ''),
    ('test_memory_target.py', 'ExactMemoryTargetTests.asyncSetUp',
     'async with asyncio.timeout(3):',
     'pending-02', ''),
    ('test_memory_target.py', 'ExactMemoryTargetTests.asyncTearDown',
     'await asyncio.wait_for(self.running, 4)',
     'pending-02', ''),
    ('test_memory_target.py', 'ExactMemoryTargetTests.cli',
     'stdout, stderr = await asyncio.wait_for(process.communicate(), 10)',
     'pending-02', ''),
    ('test_notification_delivery.py', 'DeliveryIntegrationTests.test_status_stays_responsive_while_provider_is_waiting',
     'await asyncio.wait_for(entered.wait(), 2)',
     'pending-02', ''),
    ('test_notification_delivery.py', 'DeliveryIntegrationTests.test_status_stays_responsive_while_provider_is_waiting',
     "state = await asyncio.wait_for(self.worker.call('status', priority=True), 1)",
     'pending-02', ''),
    ('test_notification_delivery.py', 'DeliveryIntegrationTests.test_cancelled_delivery_keeps_committed_budget_and_uncertainty',
     'await asyncio.wait_for(entered.wait(), 2)',
     'pending-02', ''),
    ('test_notification_provider.py', 'ProviderTests.test_cancellation_settles_invocation_before_another_can_start',
     'async with asyncio.timeout(3):',
     'pending-02', ''),
    ('test_notification_provider.py', 'ProviderTests.test_cancellation_during_spawn_does_not_leave_an_unowned_process',
     'await asyncio.wait_for(entered.wait(), 3)',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.asyncSetUp',
     'async with asyncio.timeout(4):',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.asyncSetUp',
     'async with asyncio.timeout(5):',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.asyncTearDown',
     'await asyncio.wait_for(asyncio.gather(self.task, self.bus_task), 6)',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.wait_for',
     'async with asyncio.timeout(5):',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.wait_for_delivery_health',
     'async with asyncio.timeout(5):',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.test_control_status_and_health_publish_continue_during_provider_wait',
     'await asyncio.wait_for(self.provider.entered.wait(), 4)',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.test_control_status_and_health_publish_continue_during_provider_wait',
     "reply = await asyncio.wait_for(self.request('status'), 2)",
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.test_generation_bound_stop_refuses_stale_request_and_accepts_current',
     'await asyncio.wait_for(self.task, 4)',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.test_generation_bound_stop_refuses_stale_request_and_accepts_current',
     'await asyncio.wait_for(self.bus_task, 4)',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.test_stop_control_settles_and_removes_only_owned_readiness',
     'await asyncio.wait_for(self.task, 4)',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.test_bound_memory_changes_produce_sync_pointer_without_advancing_consumer',
     'await asyncio.wait_for(task, 4)',
     'pending-02', ''),
    ('test_notification_runtime.py', 'RuntimeTests.test_manual_control_storage_fault_is_visible_through_public_status',
     'await asyncio.wait_for(entered.wait(), 4)',
     'pending-02', ''),
    ('test_notification_runtime.py', 'WorkerCreationCancellationTests.test_repeated_cancellation_waits_for_created_worker_to_close.Owned.__init__',
     'if not release.wait(3):',
     'pending-02', ''),
    ('test_notification_runtime.py', 'WorkerCreationCancellationTests.test_repeated_cancellation_waits_for_created_worker_to_close',
     'async with asyncio.timeout(3):',
     'pending-02', ''),
    ('test_notification_runtime.py', 'WorkerCreationCancellationTests.test_repeated_cancellation_waits_for_created_worker_to_close',
     'await asyncio.wait_for(closing.wait(), 3)',
     'pending-02', ''),
    ('test_notification_runtime.py', 'CleanupTests.test_memory_close_waits_for_all_watchers_after_one_fails',
     'await asyncio.wait_for(entered.wait(), 1)',
     'pending-02', ''),
    ('test_participant_instructions.py', 'MigrationTests.test_legacy_locks_exclude_cross_participant_update_and_keep_inodes',
     'self.assertTrue(reached.wait(5))',
     'pending-03', ''),
    ('test_participant_lock.py', 'OwnershipTests.test_real_process_exclusion_and_child_does_not_inherit_lock',
     'p.wait(timeout=10)',
     'pending-03', ''),
    ('test_participant_lock.py', 'OwnershipTests.test_real_process_exclusion_and_child_does_not_inherit_lock',
     'p.wait(timeout=10)',
     'pending-03', ''),
    ('test_peer_transport.py', 'ControlTransportTests.test_cancellation_during_cleanup_aborts_and_stays_cancelled',
     'await asyncio.wait_for(entered.wait(), 1)',
     'pending-02', ''),
    ('test_peer_transport.py', 'ControlTransportTests.test_timeout_closes_connection_and_does_not_claim_rollback',
     'for _ in range(20):',
     'pending-02', ''),
    ('test_platform_support.py', 'ProcessTests.test_self_is_alive_and_reaped_child_is_not',
     'self.assertEqual(child.wait(timeout=5), 0)',
     'pending-02', ''),
    ('test_platform_support.py', 'ProcessTests.test_a_vanished_process_raises_process_lookup_on_both_platforms',
     'self.assertEqual(child.wait(timeout=5), 0)',
     'pending-02', ''),
    ('test_platform_support.py', 'ProcessTests.test_process_observation_distinguishes_unreaped_exit',
     'deadline = time.monotonic() + 10',
     'pending-02', ''),
    ('test_platform_support.py', 'ProcessTests.test_process_observation_distinguishes_unreaped_exit',
     'child.wait(timeout=10)',
     'pending-02', ''),
    ('test_platform_support.py', 'AsyncProcessProbeTests.test_cancelled_callers_do_not_release_running_probe_capacity.blocked',
     'if not release.wait(5):',
     'pending-02', ''),
    ('test_platform_support.py', 'AsyncProcessProbeTests.test_cancelled_callers_do_not_release_running_probe_capacity',
     'async with asyncio.timeout(2):',
     'pending-02', ''),
    ('test_platform_support.py', 'AsyncProcessProbeTests.test_cancelled_callers_do_not_release_running_probe_capacity',
     'async with asyncio.timeout(2):',
     'pending-02', ''),
    ('test_service_workers.py', 'until',
     'async with asyncio.timeout(3):',
     'pending-02', ''),
    ('test_service_workers.py', 'ServiceWorkerTests.memory_service.BlockingStore.note',
     'if not test.release.wait(5):',
     'pending-02', ''),
    ('test_service_workers.py', 'ServiceWorkerTests.test_shutdown_settles_write_after_socket_handler_is_cancelled',
     'await asyncio.wait_for(running, 3)',
     'pending-02', ''),
    ('test_service_workers.py', 'ServiceWorkerTests.test_bridge_status_reports_unknown_while_database_is_blocked.BlockingInbox.store',
     'if not test.release.wait(5):',
     'pending-02', ''),
    ('test_service_workers.py', 'ServiceWorkerTests.test_start_initializes_database_before_publishing_endpoint.factory',
     'if not self.release.wait(5):',
     'pending-02', ''),
    ('test_service_workers.py', 'ServiceWorkerTests.test_memory_cli_reports_retryable_and_permanent_refusals_without_tracebacks',
     'stdout, stderr = await asyncio.wait_for(child.communicate(), 5)',
     'pending-02', ''),
    ('test_service_workers.py', 'ServiceWorkerTests.test_memory_cli_reports_retryable_and_permanent_refusals_without_tracebacks',
     'stdout, stderr = await asyncio.wait_for(child.communicate(), 5)',
     'pending-02', ''),
    ('test_service_workers.py', 'ServiceWorkerTests.test_memory_cli_reports_retryable_and_permanent_refusals_without_tracebacks',
     'stdout, stderr = await asyncio.wait_for(child.communicate(), 5)',
     'pending-02', ''),
    ('test_service_workers.py', 'ServiceWorkerTests.test_factory_programming_error_is_not_reported_as_incompatible_user_data',
     'stdout, stderr = await asyncio.wait_for(child.communicate(), 5)',
     'pending-02', ''),
    ('test_session.py', 'SessionTests.test_two_live_sessions_and_idempotence',
     'deadline=time.monotonic()+10',
     'pending-03', ''),
    ('test_session.py', 'SessionTests.test_two_live_sessions_and_idempotence',
     'deadline=time.monotonic()+10',
     'pending-03', ''),
    ('test_session.py', 'SessionTests.test_two_live_sessions_and_idempotence',
     'process.communicate(timeout=25)',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.stop_processes',
     'process.communicate(timeout=25)',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.stop_processes',
     'process.communicate(timeout=5)',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.test_supervisor_preserves_bridge_startup_refusal',
     'stdout, stderr = process.communicate(timeout=20)',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.test_supervisor_preserves_configuration_refusal_and_stops_bridge',
     'stdout, stderr = process.communicate(timeout=20)',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.test_supervisor_preserves_refusal_after_notifier_readiness',
     'deadline = time.monotonic()+15',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.test_supervisor_preserves_refusal_after_notifier_readiness',
     'stdout, stderr = process.communicate(timeout=20)',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.competing_command',
     'deadline = time.monotonic()+5',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.competing_command',
     'process.communicate(timeout=.2)',
     'product-deadline', 'expects the child still to be running after a short wait'),
    ('test_session.py', 'SystemdStartupTests.test_same_thread_ensure_waits_and_reuses_the_started_session',
     'stdout, stderr = competing[0].communicate(timeout=15)',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.test_stop_waits_for_start_then_stops_the_session',
     '_, stderr = competing[0].communicate(timeout=15)',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.test_rename_waits_for_start_then_refuses_a_live_session',
     '_, stderr = competing[0].communicate(timeout=15)',
     'pending-03', ''),
    ('test_session.py', 'SystemdStartupTests.test_other_thread_registration_does_not_wait_for_this_start.register_other_thread',
     'stdout, stderr = process.communicate(timeout=5)',
     'pending-03', ''),
    ('test_session_service.py', 'NativeSessionServiceTests.test_real_saved_selection_runs_pair_and_reports_guarded_shutdown.cleanup',
     'child.wait(timeout=45)',
     'pending-03', ''),
    ('test_session_service.py', 'NativeSessionServiceTests.test_real_saved_selection_runs_pair_and_reports_guarded_shutdown',
     'deadline = time.monotonic() + 35',
     'pending-03', ''),
    ('test_session_service.py', 'NativeSessionServiceTests.test_real_saved_selection_runs_pair_and_reports_guarded_shutdown',
     "self.assertEqual(child.wait(timeout=45), 0, (self.root / 'session.log').read_text())",
     'pending-03', ''),
    ('test_session_supervisor.py', 'NativeChildrenTests.cleanup_children',
     'child.wait(timeout=45)',
     'pending-03', ''),
    ('test_session_supervisor.py', 'NativeChildrenTests.wait_phase',
     'deadline = time.monotonic() + 35',
     'pending-03', ''),
    ('test_session_supervisor.py', 'NativeChildrenTests.test_real_pair_readiness_and_generation_stop_preserve_inbox',
     'deadline = time.monotonic() + 10',
     'pending-03', ''),
    ('test_session_supervisor.py', 'NativeChildrenTests.test_real_pair_readiness_and_generation_stop_preserve_inbox',
     "self.assertEqual(child.wait(timeout=45), 0, (self.root / 'runner.log').read_text())",
     'pending-03', ''),
    ('test_session_supervisor.py', 'NativeChildrenTests.test_notifier_permanent_runtime_failure_stops_bridge_and_records_refusal',
     "self.assertEqual(child.wait(timeout=45), 70, (self.root / 'runner.log').read_text())",
     'pending-03', ''),
    ('test_session_supervisor.py', 'NativeChildrenTests.test_permanent_bridge_startup_failure_is_retained_until_explicit_retry',
     "self.assertEqual(child.wait(timeout=30), 78, (self.root / 'runner.log').read_text())",
     'pending-03', ''),
    ('test_subscriptions.py', 'until',
     'async with asyncio.timeout(3):',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.start.Store.store',
     'if not release.wait(3):',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.start.Store.note',
     'if not release.wait(3):',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.check_committed_wake',
     'await asyncio.wait_for(wake, 2)',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.check_capacity',
     'await asyncio.wait_for(self.write(kind), 2)',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.test_production_bridge_factory_publishes_after_commit',
     'await asyncio.wait_for(connection.changed(), 2)',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.test_production_bridge_factory_publishes_after_commit',
     'await asyncio.wait_for(run, 3)',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.test_idle_hint_and_coalescing_are_content_free',
     'await asyncio.wait_for(connection.changed(), 1)',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.test_idle_hint_and_coalescing_are_content_free',
     'await asyncio.wait_for(connection.changed(), 1)',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.test_subscription_only_detects_existing_backlog_and_new_commit',
     'await asyncio.wait_for(scanned.wait(), 2)',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.test_subscription_only_detects_existing_backlog_and_new_commit',
     'await asyncio.wait_for(watch, 2)',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.test_rescan_only_detects_retained_work',
     'await asyncio.wait_for(sub.watch_changes(forbidden, scan, stop, rescan_interval=.03, subscriptions_enabled=False), 1)',
     'pending-02', ''),
    ('test_subscriptions.py', 'SubscriptionTests.test_reconnect_subscribes_before_recheck_without_fallback',
     'await asyncio.wait_for(sub.watch_changes(reconnecting, scan, stop, rescan_interval=None, reconnect_delays=(.01,)), 2)',
     'pending-02', ''),
    ('test_subscriptions.py', 'HubBoundTests.test_both_services_outlive_ordinary_request_deadlines.check',
     'await asyncio.wait_for(connection.changed(), 2)',
     'pending-02', ''),
    ('test_subscriptions.py', 'HubBoundTests.test_watch_does_not_hide_programming_failure',
     'await asyncio.wait_for(sub.watch_changes(broken, scan, asyncio.Event(), rescan_interval=None), 1)',
     'pending-02', ''),
    ('test_upgrade_command.py', 'CommandTests.test_external_foreground_memory_process_refuses_without_signalling_it',
     'job.wait(timeout=5)',
     'pending-03', ''),
    ('test_upgrade_documents.py', 'DocumentsTests.test_concurrent_reader_waits_for_short_metadata_publication',
     'self.assertTrue(entered.wait(1))',
     'pending-03', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.wait_until',
     'async with asyncio.timeout(5):',
     'pending-02', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.test_bridge_listener_opens_after_gate_release',
     'async with asyncio.timeout(5):',
     'pending-02', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.test_bridge_listener_opens_after_gate_release',
     'await asyncio.wait_for(task, 5)',
     'pending-02', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.test_peer_listener_waits_for_release_and_gate_fault_drains_worker',
     'await asyncio.wait_for(task, 5)',
     'pending-02', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.test_notifier_does_not_publish_or_deliver_before_release',
     'await asyncio.wait_for(notifier_task, 5)',
     'pending-02', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.test_memory_mutation_and_maintenance_remain_gated',
     'await asyncio.wait_for(maintenance, 2)',
     'pending-02', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.test_real_full_worker_queue_does_not_kill_deferred_index_task.Owner.status',
     'if not release.wait(5):',
     'pending-02', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.test_real_full_worker_queue_does_not_kill_deferred_index_task',
     'async with asyncio.timeout(2):',
     'pending-02', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.test_real_full_worker_queue_does_not_kill_deferred_index_task',
     'async with asyncio.timeout(2):',
     'pending-02', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.test_real_full_worker_queue_does_not_kill_deferred_index_task',
     'await asyncio.wait_for(asyncio.gather(*pending), 3)',
     'pending-02', ''),
    ('test_upgrade_gate.py', 'RuntimeAdmissionTests.test_real_full_worker_queue_does_not_kill_deferred_index_task',
     'await asyncio.wait_for(maintenance, 3)',
     'pending-02', ''),
    ('test_upgrade_journal.py', 'JournalTests.test_concurrent_reader_waits_for_short_metadata_publication',
     'self.assertTrue(entered.wait(1))',
     'pending-03', ''),
    ('test_upgrade_live_memory.py', 'LiveGatedMemoryTests.test_real_entrypoint_preserves_store_and_serves_repository_bound_inventory',
     'deadline = time.monotonic() + 10',
     'pending-03', ''),
    ('test_upgrade_live_memory.py', 'LiveGatedMemoryTests.test_real_entrypoint_preserves_store_and_serves_repository_bound_inventory',
     '_, error = process.communicate(timeout=10)',
     'pending-03', ''),
    ('test_upgrade_live_memory.py', 'LiveGatedMemoryTests.test_real_entrypoint_preserves_store_and_serves_repository_bound_inventory',
     'process.communicate(timeout=10)',
     'pending-03', ''),
    ('test_work_activation.py', 'ActivationTests.test_three_and_four_migrate_preserving_notes_replay_and_frozen_snapshot',
     "old.note('writer', 'decision', 'before migration', key='note-key', deadline=time.time()+600)",
     'product-deadline', DATA),
    ('test_work_activation.py', 'ActivationTests.test_public_work_counter_exhaustion_is_capacity_and_changes_nothing',
     "deadline=time.time()+600, title='Synthetic', criteria='No room', non_goals='No deployment'), 12345)",
     'product-deadline', DATA),
    ('test_work_activation.py', 'ActivationServiceTests.test_two_consumer_first_adoption_keeps_review_outside_writer_claim.mutation',
     'deadline=time.time()+600, **fields), 12345)',
     'product-deadline', DATA),
    ('test_work_activation.py', 'ActivationServiceTests.test_two_consumer_first_adoption_keeps_review_outside_writer_claim',
     "checkpoint='Initial review', next_artifact='Completed fixture', progress_deadline=time.time()+120)",
     'product-deadline', DATA),
    ('test_work_activation.py', 'ActivationServiceTests.test_two_consumer_first_adoption_keeps_review_outside_writer_claim',
     "deadline=time.time()+600, work_id=item['work_id'], if_revision=started['revision'],",
     'product-deadline', DATA),
    ('test_work_activation.py', 'ActivationServiceTests.test_two_consumer_first_adoption_keeps_review_outside_writer_claim',
     "checkpoint='Review', next_artifact='Review result', progress_deadline=time.time()+120), 12346)",
     'product-deadline', DATA),
    ('test_work_foundation.py', 'MigrationTests.test_legacy_records_identity_and_replays_survive',
     'deadline=time.time() + 600)',
     'product-deadline', DATA),
    ('test_work_guidance.py', 'GuidanceTests.test_two_process_writers_preserve_both_rules_and_original_backup',
     'out, err = child.communicate(timeout=15)',
     'pending-03', ''),
    ('test_work_maintenance.py', 'until',
     'async with asyncio.timeout(5):',
     'pending-02', ''),
    ('test_work_maintenance.py', 'MaintenanceLoopTests.test_schema4_exits_disabled_without_fault',
     'await asyncio.wait_for(self.loop(service), 2)',
     'pending-02', ''),
    ('test_work_maintenance.py', 'MaintenanceLoopTests.test_full_queue_skips_and_does_not_use_reserved_priority',
     'await asyncio.wait_for(self.loop(service), 2)',
     'pending-02', ''),
    ('test_work_maintenance.py', 'MaintenanceLoopTests.test_no_overlap_and_cancelled_waiter_drains_accepted_job.blocked',
     'if not release.wait(5):',
     'pending-02', ''),
    ('test_work_maintenance.py', 'MaintenanceLoopTests.test_startup_reports_readiness_before_sweep_and_shutdown_waits.blocked',
     'if not release.wait(5):',
     'pending-02', ''),
    ('test_work_maintenance.py', 'MaintenanceLoopTests.test_startup_reports_readiness_before_sweep_and_shutdown_waits',
     'await asyncio.wait_for(task, 2)',
     'pending-02', ''),
    ('test_work_maintenance.py', 'MaintenanceLoopTests.test_idle_subscriber_wakes_after_due_commit',
     'await asyncio.wait_for(connection.changed(), 2)',
     'pending-02', ''),
    ('test_work_policy.py', 'PolicyTests.test_lock_serializes_read_modify_write_and_preserves_both_updates',
     'out, error = process.communicate(timeout=10)',
     'pending-03', ''),
    ('test_work_policy.py', 'PolicyTests.test_two_installers_serialize_and_keep_both_participants',
     'out, error = process.communicate(timeout=15)',
     'pending-03', ''),
    ('test_work_policy.py', 'PolicyTests.test_install_reloads_configuration_after_waiting_for_lock',
     'out, error = process.communicate(timeout=15)',
     'pending-03', ''),
    ('test_work_storage.py', 'AccountingTests.test_new_credit_cannot_undercut_retained_replay_slots',
     '(time.time() + 600,))',
     'product-deadline', DATA),
    ('test_work_storage.py', 'WritePathTests.test_full_ordinary_store_preserves_all_admitted_controls_and_note_progress',
     "('work:' + work_id, 'fingerprint', seq, time.time(), time.time() + 600,",
     'product-deadline', DATA),
    ('test_waiting.py', 'AsyncWaitTests.test_condition_true_at_the_deadline_succeeds',
     'ready_at = loop.time() + .05',
     'product-deadline', "tests the wait helper's own deadline boundary"),
]
