"""Every coordination wait in tests/ that does not yet use `waiting`, and the product-deadline
values that look like one.

Built for the test reliability sprint (docs/sprints/2026-09-22-test-reliability/). Each entry is
(file, function, source line, status, reason). A `pending-02` or `pending-03` entry is a
coordination wait that chunk 02 or 03 converts to `waiting` and then removes from this list; a
file that chunk 02 does not name belongs to chunk 03. A `product-deadline` entry stays, with its
reason. `test_wait_inventory` checks this list against the source.
"""
DATA = 'product data: a deadline or expiry value passed to the code under test, not a wait'

ENTRIES = [
    ('test_delivery_ledger.py', 'LedgerTests.test_outgoing_and_incoming_capacity_are_independent',
     "self.store.outgoing('uds:/tmp/target.sock', 'body', 'next', 'id', time.time()+60)",
     'product-deadline', DATA),
    ('test_delivery_ledger.py', 'LedgerTests.test_outgoing_and_incoming_capacity_are_independent',
     "self.store.outgoing('uds:/tmp/target.sock', 'body', 'next', 'other', time.time()+60)",
     'product-deadline', DATA),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_fetch_evidence_timeout_never_appends_a_second_reply.blocked',
     'release.wait(2)',
     'product-deadline', "holds the synthetic peer past the product's control deadline"),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_definite_connect_failure_is_durable_without_replay',
     'deadline = time.time()+60',
     'product-deadline', DATA),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_cancelled_native_send_is_never_replayed',
     'deadline = time.time() + 60',
     'product-deadline', DATA),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_control_timeout_preserves_unknown_and_late_send_reservation.blocked',
     'release.wait(2)',
     'product-deadline', "holds the synthetic peer past the product's control deadline"),
    ('test_delivery_ledger.py', 'SocketEvidenceTests.test_control_timeout_preserves_unknown_and_late_send_reservation',
     'deadline = time.time() + 60',
     'product-deadline', DATA),
    ('test_memory.py', 'Base.note',
     "kw['deadline'] = time.time() + 600",
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_an_empty_snapshot_and_a_keyed_write_are_both_charged',
     "self.s.note('writer', 'finding', 'keyed', key='k1', deadline=time.time()+600)",
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_an_in_window_idempotency_key_is_never_evicted_to_make_room',
     'deadline = time.time() + 600',
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_the_retry_deadline_is_echoed_and_the_horizon_reported',
     'deadline = time.time() + 600',
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_deduplication_state_is_retained_only_to_its_deadline',
     "self.note('kept', key='fresh', deadline=time.time()+600)",
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_an_idempotent_write_requires_a_deadline_fixed_before_the_first_send',
     'deadline=time.time()+memory.IDEM_TTL+60)',
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_a_retry_after_its_deadline_is_refused_rather_than_appended',
     'deadline = time.time() + 0.3',
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_a_duplicate_carrying_a_changed_deadline_is_refused',
     'deadline = time.time() + 600',
     'product-deadline', DATA),
    ('test_memory.py', 'WriteTests.test_the_reported_author_is_part_of_the_content_fingerprint',
     'deadline = time.time() + 600',
     'product-deadline', DATA),
    ('test_memory.py', 'LifecycleTests.test_a_crash_between_commit_and_response_is_survived_and_recovered',
     'deadline = time.time() + 600',
     'product-deadline', DATA),
    ('test_memory.py', 'LifecycleTests.test_cli_records_scope_provenance_and_expiry',
     "'--expires',str(time.time()+3600)],capture_output=True,text=True)",
     'product-deadline', DATA),
    ('test_memory.py', 'LifecycleTests.test_the_cli_can_continue_recall_and_status_pages',
     'deadline = str(time.time()+600)',
     'product-deadline', DATA),
    ('test_session.py', 'SystemdStartupTests.competing_command',
     'process.communicate(timeout=.2)',
     'product-deadline', 'expects the child still to be running after a short wait'),
    ('test_work_activation.py', 'ActivationTests.test_three_and_four_migrate_preserving_notes_replay_and_frozen_snapshot',
     "old.note('writer', 'decision', 'before migration', key='note-key', deadline=time.time()+600)",
     'product-deadline', DATA),
    ('test_work_activation.py', 'ActivationTests.test_public_work_counter_exhaustion_is_capacity_and_changes_nothing',
     "deadline=time.time()+600, title='Synthetic', criteria='No room', non_goals='No deployment'), 12345)",
     'product-deadline', DATA),
    ('test_work_activation.py', 'ActivationServiceTests.test_two_consumer_first_adoption_keeps_review_outside_writer_claim.mutation',
     'deadline=time.time()+600, **fields), 12345)',
     'product-deadline', DATA),
    ('test_work_activation.py', 'ActivationServiceTests.test_two_consumer_first_adoption_keeps_review_outside_writer_claim',
     "checkpoint='Initial review', next_artifact='Completed fixture', progress_deadline=time.time()+120)",
     'product-deadline', DATA),
    ('test_work_activation.py', 'ActivationServiceTests.test_two_consumer_first_adoption_keeps_review_outside_writer_claim',
     "deadline=time.time()+600, work_id=item['work_id'], if_revision=started['revision'],",
     'product-deadline', DATA),
    ('test_work_activation.py', 'ActivationServiceTests.test_two_consumer_first_adoption_keeps_review_outside_writer_claim',
     "checkpoint='Review', next_artifact='Review result', progress_deadline=time.time()+120), 12346)",
     'product-deadline', DATA),
    ('test_work_foundation.py', 'MigrationTests.test_legacy_records_identity_and_replays_survive',
     'deadline=time.time() + 600)',
     'product-deadline', DATA),
    ('test_work_storage.py', 'AccountingTests.test_new_credit_cannot_undercut_retained_replay_slots',
     '(time.time() + 600,))',
     'product-deadline', DATA),
    ('test_work_storage.py', 'WritePathTests.test_full_ordinary_store_preserves_all_admitted_controls_and_note_progress',
     "('work:' + work_id, 'fingerprint', seq, time.time(), time.time() + 600,",
     'product-deadline', DATA),
    ('test_waiting.py', 'AsyncWaitTests.test_condition_true_at_the_deadline_succeeds',
     'ready_at = loop.time() + .05',
     'product-deadline', "tests the wait helper's own deadline boundary"),
]
